root:
    path: /
    defaults: { _controller: AcmeDemoBundle:Main:index }
random:
    path: /random/{limit}
    defaults: { _controller: AcmeDemoBundle:Random:index }
main:
    path: /main
    defaults: { _controller: AcmeDemoBundle:Main:index }
